# Generated by Django 5.1.3 on 2025-03-10 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_grocerylist_created_at_recipe_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptiontier',
            name='stripe_price_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
