# Generated by Django 5.1.3 on 2025-03-13 11:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_remove_recipe_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='useractivity',
            name='user_action_idx',
        ),
        migrations.AddField(
            model_name='useractivity',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useractivity',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='action',
            field=models.CharField(choices=[('create_meal', 'Created Meal Plan'), ('update_meal', 'Updated Meal Plan'), ('delete_meal', 'Deleted Meal Plan'), ('create_recipe', 'Created Recipe'), ('update_recipe', 'Updated Recipe'), ('delete_recipe', 'Deleted Recipe'), ('subscription', 'Subscription Change'), ('login', 'Login'), ('logout', 'Logout')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='useractivity',
            index=models.Index(fields=['user', 'action', 'timestamp'], name='dashboard_u_user_id_4d1a7e_idx'),
        ),
    ]
