# Generated by Django 5.1.3 on 2025-03-13 13:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_alter_useractivity_action'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='cook_time',
            field=models.CharField(default='45 mins', max_length=20),
        ),
        migrations.AddField(
            model_name='recipe',
            name='day_index',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='difficulty',
            field=models.CharField(default='Intermediate', max_length=20),
        ),
        migrations.AddField(
            model_name='recipe',
            name='meal_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.mealplan'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='meal_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='nutrition_info',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='recipe',
            name='prep_time',
            field=models.CharField(default='30 mins', max_length=20),
        ),
        migrations.AddField(
            model_name='recipe',
            name='servings',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='recipe',
            name='tips',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterUniqueTogether(
            name='recipe',
            unique_together={('meal_plan', 'meal_type', 'day_index')},
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['meal_plan', 'meal_type', 'day_index'], name='recipe_meal_idx'),
        ),
    ]
