# Generated by Django 5.1.3 on 2025-03-13 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_recipe_cook_time_recipe_day_index_recipe_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptiontier',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscriptiontier',
            name='stripe_product_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subscriptiontier',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='subscriptiontier',
            index=models.Index(fields=['stripe_price_id'], name='stripe_price_idx'),
        ),
    ]
