# Generated by Django 5.1.3 on 2025-03-14 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_subscriptiontier_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='is_ai_generated',
            field=models.BooleanField(default=False),
        ),
    ]
