# Generated by Django 5.1.3 on 2025-03-17 15:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_alter_usersubscription_start_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='grocerylist',
            name='meal_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.mealplan'),
        ),
        migrations.AddIndex(
            model_name='grocerylist',
            index=models.Index(fields=['meal_plan'], name='grocery_meal_plan_idx'),
        ),
    ]
