# Generated by Django 4.2.5 on 2025-03-21 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_subscriptiontier_meal_plan_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptiontier',
            name='tier_type',
            field=models.CharField(choices=[('one_time', 'Pay Once'), ('weekly', 'Weekly Plan'), ('monthly', 'Monthly Plan')], db_index=True, max_length=20),
        ),
    ]
