# Generated by Django 4.2.5 on 2025-03-27 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_alter_subscriptiontier_tier_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='orders_used',
            field=models.IntegerField(default=0),
        ),
    ]
